### ISSUE TITLE
Use internationalization api for currency formatting

### ISSUE THREAD

**Issue by anthony-fdez** [AlejandroV01/Stock-App#4]
We need to try and use the Intl api for every currency formatting, it will automatically format the currency depending on what country the user is visiting. It is everything automatic and will save us a ton of time

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

**Comment by AlejandroV01** [comment]
Easy 1 liner

**Comment by AlejandroV01** [comment]
Re-open because right when I closed this I realized that the currency symbol won't change
